### ISSUE TITLE
Suggestion | Native clothing names

### ISSUE THREAD

**Issue by JajarGaming** [pedr0fontoura/fivem-appearance#75]
This could be used to display clothing piece and texture names.

Data can be gathered from: https://github.com/root-cause/v-clothingnames

**Comment by pedr0fontoura** [comment]
This would be a nice addition.

It would require some considerable changes to the usability and design of the interface.

I already researched this and have the code to do it, clothing data can be extracted directly from the game, and there is no need to use an external data source.

But I'm not sure if it's worth adding new complex features like this one to the script, since people decided to create a bunch of copies of this repo and maintain it with X framework support, instead of contributing to the original one LOL.

**Comment by JajarGaming** [comment]
Could you give more details on extracting the clothing data straight through the game?
